### ISSUE TITLE
circos error

### ISSUE THREAD

**Issue by tinyfallen** [zhangrengang/Centromics#10]
hi dear developer,

Thanks for the software!

It seemed to be an error on circos plotting, but I have no idea how to solve it. Could you please give me some advices?

```
23-09-07 11:33:38 [INFO] finished with 0 commands uncompleted
23-09-07 11:33:38 [INFO] Count inter and intra-chromosomal signals
23-09-07 11:42:06 [INFO] New check point file: `/data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/tmp/cent.cent.hic.count.100000.ok`
23-09-07 11:42:06 [INFO] Copy `/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/circos` to `/data2/home/ydn/yty/pame/0reassembly/9.structure/centromere`
23-09-07 11:42:19 [INFO] run CMD: `cd /data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos && circos -conf ./circos.conf`
Traceback (most recent call last):
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos/circos.svg' -> '/data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos/circos.svg.bk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/bin/centromics", line 33, in <module>
    sys.exit(load_entry_point('Centromics==0.3', 'console_scripts', 'centromics')())
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 272, in main
    pipeline.run()
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 133, in run
    self.run_circos(tr_bed=tr_bed, tr_labels=tr_labels,
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 153, in run_circos
    Circos.centomics_plot(self.genome, wkdir, *args, **kargs)
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 386, in centomics_plot
    fmt_svg(svgfile)
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 633, in fmt_svg
    bksvgfile, svgfile = backup_file(svgfile)
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/small_tools.py", line 288, in backup_file
    shutil.move(input_file, input_file_bk)
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/shutil.py", line 805, in move
    copy_function(src, real_dst)
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/export/home/ydn/.conda/envs/yty/envs/centromics/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos/circos.svg'
```

Best regards.

**Comment by zhangrengang** [comment]
Please re-run `cd /data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos && circos -conf ./circos.conf`, and see what errors raise.

**Comment by tinyfallen** [comment]
Thanks for the timely reply, the error message said:

```
$ circos -conf ./circos.conf
debuggroup summary 0.78s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
debuggroup summary 0.79s current working directory /data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos
debuggroup summary 0.79s command /export/home/ydn/.conda/envs/yty/envs/centromics/bin/circos -conf ./circos.conf
debuggroup summary 0.79s loading configuration from file ./circos.conf
debuggroup summary 0.79s found conf file ./circos.conf
debuggroup summary 0.96s debug will appear for these features: output,summary
debuggroup summary 0.96s bitmap output image ./circos.png
debuggroup summary 0.96s SVG output image ./circos.svg
debuggroup summary 0.96s parsing karyotype and organizing ideograms
debuggroup summary 0.96s karyotype has 0 chromosomes of total size 0

  *** CIRCOS ERROR ***

      cwd:
      /data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/cent.circos

      command: /export/home/ydn/.conda/envs/yty/envs/centromics/bin/circos -conf
      ./circos.conf

  No ideograms to draw. Either define some in 'chromosomes' parameter or set

      chromosomes_display_default = yes

  If you are having trouble debugging this error, first read the best practices
  tutorial for helpful tips that address many common problems

      http://www.circos.ca/documentation/tutorials/reference/best_practices

  The debugging facility is helpful to figure out what's happening under the
  hood

      http://www.circos.ca/documentation/tutorials/configuration/debugging

  If you're still stumped, get support in the Circos Google Group.

      http://groups.google.com/group/circos-data-visualization

  Please include this error, all your configuration, data files and the version
  of Circos you're running (circos -v). Do not email me directly -- please use
  the group.

  Stack trace:
 at /export/home/ydn/.conda/envs/yty/envs/centromics/bin/../lib/Circos/Error.pm line 425.
        Circos::Error::fatal_error("ideogram", "no_ideograms_to_draw") called at /export/home/ydn/.conda/envs/yty/envs/centromics/bin/../lib/Circos/Ideogram.pm line 318
        Circos::Ideogram::parse_chromosomes(HASH(0x55e61a86da10)) called at /export/home/ydn/.conda/envs/yty/envs/centromics/bin/../lib/Circos.pm line 247
        Circos::run("Circos", "_cwd", "/data2/home/ydn/yty/pame/0reassembly/9.structure/centromere/c"..., "_argv", "-conf ./circos.conf", "configfile", "./circos.conf") called at /export/home/ydn/.conda/envs/yty/envs/centromics/bin/circos line 536
```

I found the data/genome_karyotype.txt was an empty file and there was a line recording 'chromosomes_display_default = yes' in the circos.conf.
```
$ ll data/
total 292K
-rw-r--r-- 1 ydn biosge 125K Sep  7 23:44 genome_gc.txt
-rw-r--r-- 1 ydn biosge    0 Sep  7 23:44 genome_karyotype.txt
-rw-r--r-- 1 ydn biosge 127K Sep  7 23:44 hic_inter.density.txt
-rw-r--r-- 1 ydn biosge  35K Sep  7 23:44 tr_density.txt

$ cat circos.conf

<<include ./etc/colors_fonts_patterns.conf>>
<<include ./colors.conf>>

<<include ./etc/ideogram.conf>>
<<include ./etc/ticks.conf>>

<image>
<<include ./etc/image.conf>>
</image>

karyotype   = data/genome_karyotype.txt

chromosomes_units = 0.002r
chromosomes_display_default = yes

<<include ./histogram.conf>>


<<include ./etc/housekeeping.conf>>
data_out_of_range* = trim

```

**Comment by zhangrengang** [comment]
You need to set `-chr_prefix`. The default to recognize a chromosome is starting with "chr". It is for removing unplaced short contigs from the circos plot.

**Comment by tinyfallen** [comment]
Thanks for the reply! I have tried to mock a karyotype.txt file to fit Circos and it goes smoothly.
```
$ cat karyotype.txt
chr - Pa01 Pa01 0 96338841 Pa01
chr - Pa02 Pa02 0 105624931 Pa02
chr - Pa03 Pa03 0 97012155 Pa03
chr - Pa04 Pa04 0 58046398 Pa04
chr - Pa05 Pa05 0 81218143 Pa05
chr - Pa06 Pa06 0 62867237 Pa06
chr - Pa07 Pa07 0 78837527 Pa07
chr - Pa08 Pa08 0 59714246 Pa08
chr - Pa09 Pa09 0 51273300 Pa09
chr - Pa10 Pa10 0 48947417 Pa10
chr - Pa11 Pa11 0 52942098 Pa11
chr - Pa12 Pa12 0 48729441 Pa12
```

**Comment by zhangrengang** [comment]
Great! You can set `-chr_prefix Pa` for this case.
