### ISSUE TITLE
NameError: name 'pp' is not defined

### ISSUE THREAD

**Issue by mushroomOK** [zhangrengang/Centromics#12]
Hi, I got an error about "NameError: name 'pp' is not defined". 
My command: "centromics -p 128 -l $hifi -g V127_CBMhap1.fasta -pre V127_CBMhap1-hifi_hifi -hic ./juicer/aligned/merged_nodups.txt"

"###STDOUT:<<  >>
###STDERR:<< Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:121)
	at juicebox.data.DatasetReaderV2.getMagicString(DatasetReaderV2.java:111)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:57)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
 >>
Traceback (most recent call last):
  File "/home/wangj/miniconda3/envs/RepCent/bin/centromics", line 33, in <module>
    sys.exit(load_entry_point('Centromics==0.3', 'console_scripts', 'centromics')())
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 272, in main
    pipeline.run()
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 120, in run
    hic_bed = self.run_hic()
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 254, in run_hic
    out1, out2 = count_obs(self.hic, chrLst=self.d_seqL.keys(), prefix=hic_count, tmpdir=tmpdir,
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Hic.py", line 17, in count_obs
    hic2signals(fout1, fout2, 
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Juicer.py", line 97, in hic2signals
    d_files = hic2matrix(res=res, **kargs)
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Juicer.py", line 90, in hic2matrix
    d_files = run_juicerbox(inHic, chr_combs, outdir=outdir, res=res, norm=norm, cmd_opts=cmd_opts)
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Juicer.py", line 23, in run_juicerbox
    run_job(cmd_file, cmd_list=cmds, **cmd_opts)
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/RunCmdsMP.py", line 533, in run_job
    exit = run_tasks(cmd_list, tc_tasks=tc_tasks, mode=mode, grid_opts=grid_opts,
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/RunCmdsMP.py", line 189, in run_tasks
    job_status = pp_run(cmd_list, processors=tc_tasks)
  File "/home/wangj/miniconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/RunCmdsMP.py", line 322, in pp_run
    job_server = pp.Server(processors, ppservers=ppservers)
NameError: name 'pp' is not defined"

The file of "slurm-2527306_127.txt" includes the whole working log. If you need more information, please let me know. Thanks!
[hs_err_pid244723.log](https://github.com/zhangrengang/Centromics/files/13406999/hs_err_pid244723.log)
[slurm-2527306_127.txt](https://github.com/zhangrengang/Centromics/files/13407003/slurm-2527306_127.txt)

**Comment by zhangrengang** [comment]
I sorry that you need to install `pp` module via `conda install pp`. I will update the `yaml` file soon.
