### ISSUE TITLE
###STDERR:<< Exception in thread "main" java.lang.NullPointerException 	at juicebox.tools.clt.old.Dump.extractChromosomeRegionIndices(Dump.java:467) 	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:364) 	at juicebox.tools.HiCTools.main(HiCTools.java:85)  >>

### ISSUE THREAD

**Issue by LaForever** [zhangrengang/Centromics#18]
Hello, recently I encountered the same error when running Centromics on different servers. My command is ：
centromics -l hifi.clean.fasta.gz -g nogap_verkkofilling_Chr1_12.fasta -pre hifihic -hic merged_nodups.hic -tmpdir hifihic.tmp -ncpu 20
Here is the error message：
24-03-12 10:01:54 [INFO] run CMD: `java -jar /public/home/zhaojiale/software/yes/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/bin/juicebox_tools.jar dump observed NONE merged_nodups.hic Chr2 Chr9 BP 100000 /public/home/zhaojiale/KLF/centromics/hifihic.tmp/hifihic.hic.matrix/Chr2-Chr9.100000.mat`
24-03-12 10:01:55 [WARNING] exit code 1 for CMD `java -jar /public/home/zhaojiale/software/yes/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/bin/juicebox_tools.jar dump observed NONE merged_nodups.hic Chr2 Chr6 BP 100000 /public/home/zhaojiale/KLF/centromics/hifihic.tmp/hifihic.hic.matrix/Chr2-Chr6.100000.mat`: 
24-03-12 10:01:55 [WARNING] 
###STDOUT:<< HiC file version: 8
 >>
###STDERR:<< Exception in thread "main" java.lang.NullPointerException
	at juicebox.tools.clt.old.Dump.extractChromosomeRegionIndices(Dump.java:467)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:364)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
 >>
I'm not sure if this is a problem with the Java version, but the error I encountered is the same on both servers.

**Comment by zhangrengang** [comment]
I have no sense about the error. You can just run the command `java -jar /public/home/zhaojiale/software/yes/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/bin/juicebox_tools.jar dump observed NONE merged_nodups.hic Chr2 Chr6 BP 100000 /public/home/zhaojiale/KLF/centromics/hifihic.tmp/hifihic.hic.matrix/Chr2-Chr6.100000.mat` to debug, or try new version of  juicebox_tools (https://github.com/aidenlab/juicer/).
