### ISSUE TITLE
circos/circos.

### ISSUE THREAD

**Issue by xfcypeng** [zhangrengang/Centromics#3]
3-05-14 16:01:34 [INFO] run CMD: `cd /media/ps/4T/Centromics/HapA/cent-output/hifi.circos && circos -conf ./circos.conf`
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/media/ps/4T/Centromics/HapA/cent-output/hifi.circos/circos.svg' -> '/media/ps/4T/Centromics/HapA/cent-output/hifi.circos/circos.svg.bk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/RepCent/bin/centromics", line 33, in <module>
    sys.exit(load_entry_point('Centromics==0.3', 'console_scripts', 'centromics')())
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 272, in main
    pipeline.run()
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 133, in run
    self.run_circos(tr_bed=tr_bed, tr_labels=tr_labels,
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 153, in run_circos
    Circos.centomics_plot(self.genome, wkdir, *args, **kargs)
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 386, in centomics_plot
    fmt_svg(svgfile)
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 633, in fmt_svg
    bksvgfile, svgfile = backup_file(svgfile)
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/small_tools.py", line 288, in backup_file
    shutil.move(input_file, input_file_bk)
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/shutil.py", line 805, in move
    copy_function(src, real_dst)
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ps/anaconda3/envs/RepCent/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/media/ps/4T/Centromics/HapA/cent-output/hifi.circos/circos.svg'

**Comment by zhangrengang** [comment]
Hi, it seems `circos` failed. Please post more log before the error.
