### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by JierongWang** [zhangrengang/Centromics#9]
你好，我用如下命令跑：centromics -l ~/wang/cleanData/singleCell/hybrid/pacbioHifi/AZ-2.hifi_reads.fq.gz -g ../AZ-2hap2chr18.fa， 出现了错误，请问我该怎么解决呢？谢谢！
23-08-31 10:21:19 [INFO] run CMD: `blastn -query ../AZ-2hap2chr18.fa -db /stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/tmp/centomics.blast/centomics..blastqry -out /stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/tmp/centomics.blast/centomics..blastqry.blastout -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen sstrand' -num_threads 28 -task blastn-short -word_size 9 -dust no -soft_masking false`
23-08-31 10:21:26 [INFO] Parse blast out
23-08-31 10:21:26 [INFO] New check point file: `/stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/tmp/centomics.centomics.trf.count.ok`
23-08-31 10:21:26 [INFO] Copy `/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/circos` to `/stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/cent-output`
Traceback (most recent call last):
  File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/bin/centromics", line 33, in <module>
    sys.exit(load_entry_point('Centromics==0.3', 'console_scripts', 'centromics')())
  File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 272, in main
    pipeline.run()
  File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 133, in run
    self.run_circos(tr_bed=tr_bed, tr_labels=tr_labels,
  File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 153, in run_circos
    Circos.centomics_plot(self.genome, wkdir, *args, **kargs)
  File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 309, in centomics_plot
    _n = n = stack_bed(tr_bed, tr_file, window_size=window_size)
  File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 427, in stack_bed
    for i in range(counts.shape[1]):
IndexError: tuple index out of range

**Comment by zhangrengang** [comment]
抱歉遗漏了你的邮件。这个问题看起来是前面串联重复的结果是空的，导致后面画图时报错，可以检查下。

**Comment by JierongWang** [comment]
老师好，
根据您的建议，我已检查了trf的结果，发现里面文件并不是空的。为了更有效率的交流，老师能否方便给我微信号或qq。谢谢老师！
| |
wangjrhb
|
|
***@***.***
|
On 9/8/2023 ***@***.***> wrote：

抱歉遗漏了你的邮件。这个问题看起来是前面串联重复的结果是空的，导致后面画图时报错，可以检查下。

**Comment by zhangrengang** [comment]
我没法公开这个，你可以私下给我发邮件。

**Comment by Laner595** [comment]
> 你好，我用如下命令跑：centromics -l ~/wang/cleanData/singleCell/hybrid/pacbioHifi/AZ-2.hifi_reads.fq.gz -g ../AZ-2hap2chr18.fa， 出现了错误，请问我该怎么解决呢？谢谢！ 23-08-31 10:21:19 [INFO] run CMD: `blastn -query ../AZ-2hap2chr18.fa -db /stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/tmp/centomics.blast/centomics..blastqry -out /stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/tmp/centomics.blast/centomics..blastqry.blastout -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen sstrand' -num_threads 28 -task blastn-short -word_size 9 -dust no -soft_masking false` 23-08-31 10:21:26 [INFO] Parse blast out 23-08-31 10:21:26 [INFO] New check point file: `/stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/tmp/centomics.centomics.trf.count.ok` 23-08-31 10:21:26 [INFO] Copy `/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/circos` to `/stor9000/apps/users/NWSUAF/2010110076/wang/hybrid/assembly/hifiasm16/AZ-2/singelCell/02_hic/011_juicerboxAZ-2h2/3d-dna/juicerbox/centromics/cent-output` Traceback (most recent call last): File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/bin/centromics", line 33, in sys.exit(load_entry_point('Centromics==0.3', 'console_scripts', 'centromics')()) File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 272, in main pipeline.run() File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 133, in run self.run_circos(tr_bed=tr_bed, tr_labels=tr_labels, File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/pipe.py", line 153, in run_circos Circos.centomics_plot(self.genome, wkdir, *args, **kargs) File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 309, in centomics_plot _n = n = stack_bed(tr_bed, tr_file, window_size=window_size) File "/stor9000/apps/users/NWSUAF/2010110076/anaconda3/envs/RepCent/lib/python3.8/site-packages/Centromics-0.3-py3.8.egg/Centromics/Circos.py", line 427, in stack_bed for i in range(counts.shape[1]): IndexError: tuple index out of range

Hello, I also had the same problem, how did you solve it?
